straight_line_count = 1
dashed_line_count = 1
polyline_count = 1
doodle_count = 1
rectangle_count = 1
circle_count = 1
bezier_count = 1
text_count = 1
image_count = 1
spline_count = 1
temp_count = 0
joint_color = [155, 224, 229, 255]
model_exit = True
